export const reviewsSlider = [
    {
        text: 'THIS WAS AN EXQUISITE PRACTICE, MALLORY! GENTLE, POWERFUL, AND CHALLENGING. IT FELT LIKE A REAL BALM FOR A STRESSFUL AND UNCERTAIN WEEK. I PARTICULARLY LOVED THE AB WORK!',
        author: 'Courtney',
    },
    {
        text: 'MALLORY&apos;S PRESENCE IS LIFE CHANGING. I LOVE HOW SHE LEADS WITH GRACE, AND INVITES US INTO A FULLER BECOMING, FULL OF SELF-LOVE AND INTEGRITY TOWARD HOW THAT RIPPLES OUT TO THE COLLECTIVE. SETTLED BODIES SETTLE OTHER BODIES. WHAT A NOURISHMENT THIS WAS.',
        author: 'Lindsay',
    },
    {
        text: 'THANK YOU MALLORY, YOU ELEGANT AND SINCERE SOUL, FOR MAKING ME FEEL ENTITLED TO GIVE VOICE TO THESE NUANCES, WHILE PUTTING THE SPOTLIGHT WHERE IT IS HONEST TO ORIENT. PLEASE, TAKE THIS CLASS WHENEVER YOU FEEL ANGRY, SAD OR, OF COURSE, GRATEFUL. MALLORY&apos;S LESSONS ARE NEVER BANAL OR OBVIOUS, AND FOR SURE, SHE&apos;S ALWAYS IN OUR LIST OF GRATITUDE.',
        author: 'Chiara',
    },
];